#!/usr/bin/env bash
set -eu
APP_ID="$1"
FILE_ID="$2"
CONTENT_DIR="$3"
VERSION="$4"

cat << EOF
"workshopitem"
{
    "appid"            "${APP_ID}"
    "publishedfileid"  "${FILE_ID}"
    "visibility"       "0"
    "title"            "Centralized Climate Control 2.0"
    "contentfolder"    "${CONTENT_DIR}"
    "previewfile"      "${CONTENT_DIR}/About/preview.png"
    "changenote"       "See the [url=https://github.com/Adirelle/CentralizedClimateControl/releases/tag/${VERSION}]release on Github[/url]."
}
EOF
