SLN_FILE = CentralizedClimateControl.sln

DOTNET = dotnet.exe
DOTNET_FORMAT_ARGS = --no-restore -wsa info $(SLN_FILE)

PRETTIER = npx -q prettier
NPM = npm

PRETTIER_TARGETS = .github 1.3 About docs *.json *.md

.PHONY: all cleaner format lint quicktest release

all: format

cleaner:
	rm -rf node_modules

format: | node_modules
	"$(DOTNET)" tool run dotnet-format $(DOTNET_FORMAT_ARGS)
	$(PRETTIER) --write $(PRETTIER_TARGETS)

lint: | node_modules
	"$(DOTNET)" tool run dotnet-format --check $(DOTNET_FORMAT_ARGS)
	$(PRETTIER) --check $(PRETTIER_TARGETS)

release: VERSION=$(shell changelog suggest)
release:
	changelog release --suggest --yes
	$(MAKE) -f .build/Makefile.metadata BUILD_DIR=.release VERSION="$(VERSION)"
	$(PRETTIER) --write .release
	cd .release; cp -prv * ..
	rm -rf .release
	git add CHANGELOG.md About
	git commit -m "Release $(VERSION)"
	.build/scripts/changelog "$(VERSION)" | git tag "$(VERSION)" -a -F -

quicktest:
	cd "$(RIMWORLD_PATH)"; exec ./RimWorldWin64.exe -savedatafolder=QuickTestSaveData

node_modules: package-lock.json
	$(NPM) install
	@touch $@
