#!/usr/bin/env bash
set -eu
APP_ID=${1:-${STEAM_APP_ID}}
FILE_ID=${2:-${STEAM_FILE_ID}}
DIST_DIR=${3}
VERSION=${4:-${VERSION}}

THERE=`pwd -L`

cat << EOF
"workshopitem"
{
    "appid"            "${APP_ID}"
    "publishedfileid"  "${FILE_ID}"
    "visibility"       "0"
    "title"            "Centralized Climate Control 2.0"
    "contentfolder"    "${THERE}/${DIST_DIR}"
    "previewfile"      "${THERE}/${DIST_DIR}/About/preview.png"
    "changenote"       "See the [url=https://github.com/Adirelle/CentralizedClimateControl/releases/tag/${VERSION}]release on Github[/url]."
}
EOF
