name: Build the mod

on:
  push:
    branches:
      - main
    tags:
      - 2.*
  pull_request: ~

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  MOD_NAME: CentralizedClimateControl

jobs:
  build:
    name: Build the mod
    runs-on: windows-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Install pandoc
        run: choco install -r pandoc

      - name: Extract the version string
        id: version
        shell: bash
        run: |
          VERSION="$(git describe --always)"
          echo "::set-output name=version::${VERSION%-g*}"
          case "$VERSION" in
            *-*-g*|*alpha*|*beta*)
              echo "::set-output name=prerelease::true"
            ;;
            *)
              echo "::set-output name=prerelease::false"
            ;;
          esac

      - name: Build all
        shell: bash
        run: |
          make package VERSION="${{ steps.version.outputs.version }}" RELEASE_TYPE="Release"

      - name: Upload the distribution
        uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: "dist/**"

      - name: Create the release
        if: ${{ ! github.base_ref }}
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}
          commit: ${{ github.sha }}
          prerelease: ${{ steps.version.outputs.prerelease }}
          bodyFile: dist/${{ env.MOD_NAME }}/About/Changelog.txt
          artifacts: ${{ env.MOD_NAME }}.zip
          artifactContentType: application/zip
          token: ${{ github.token }}
          allowUpdates: true
          replacesArtifacts: true
