name: Build the mod

on:
  push:
    branches:
      - main
    tags:
      - 2.*
  pull_request: ~

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build the mod
    runs-on: windows-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Install pandoc
        run: choco install -r pandoc

      - name: Extract the version from the tag
        if: ${{ startsWith(github.ref, 'refs/tags/2.') }}
        id: version
        shell: bash
        run: |
          echo "::set-output name=version::${{ github.ref[10:] }}"

      - name: Build the package
        shell: bash
        run: |
          make package VERSION="${{ steps.version.outputs.version }}" RELEASE_TYPE="Release"

      - name: Upload the distribution
        uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: "dist/**"

      - name: Create a Github release
        if: ${{ steps.version.outputs.version }}
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}
          commit: ${{ github.sha }}
          bodyFile: dist/RELEASE_CHANGELOG.md
          artifacts: dist/CentralizedClimateControl-${{ steps.version.outputs.version }}.zip
          artifactContentType: application/zip
          token: ${{ github.token }}
          allowUpdates: true
          replacesArtifacts: true
