name: Build a debug version of the mod

on:
  push:
    branches:
      - main
  pull_request: ~

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build the mod
    runs-on: windows-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Install dependencies
        run: |
          dotnet restore --locked-mode
          choco install -r pandoc

      - name: Build the mod content
        shell: bash
        run: make content

      - name: Upload it
        uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: "dist/**"
