name: build-debug

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore
      working-directory: Source/CentralizedClimateControl

    - name: Build
      run: dotnet build --configuration Debug --no-restore
      working-directory: Source/CentralizedClimateControl

    - name: Version
      run: echo "::set-output name=version::$(git describe)"
      id: version

    - name: Update version information
      run: sed -i -e 's/2.0.0.0/${{ steps.version.outputs.version }}/' About\Manifest.xml About\ModSync.xml
      shell: bash

    - name: Create the package
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'CentralizedClimateControl.zip'
        exclusions: '*.git* /Source/*'

    - name: Create the release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ steps.version.outputs.version }}
        draft: true
        prerelease: false
        bodyFile: About/Changelog.txt
        artifacts: "CentralizedClimateControl.zip"
        artifactContentType: application/zip
        token: ${{ github.token }}
        allowUpdates: true
        replacesArtifacts: true
